<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbxHbhp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbxHbhp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCbxHbhp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCbxHbhp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCbxHbhp\App_KernelDevDebugContainer([
    'container.build_hash' => 'CbxHbhp',
    'container.build_id' => '235bf035',
    'container.build_time' => 1583776402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbxHbhp');
