<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA724Mxc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA724Mxc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA724Mxc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA724Mxc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA724Mxc\App_KernelDevDebugContainer([
    'container.build_hash' => 'A724Mxc',
    'container.build_id' => '0fac2625',
    'container.build_time' => 1583839239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA724Mxc');
