<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETSfJr4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETSfJr4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerETSfJr4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerETSfJr4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerETSfJr4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ETSfJr4',
    'container.build_id' => '9874c76c',
    'container.build_time' => 1583776763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETSfJr4');
